[project]
name = "version-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai[tools]>=0.140.0,<1.0.0",
    "fpdf2>=2.8.3",
    "streamlit>=1.46.1",
]
